#if !canImport(ObjectiveC)
import XCTest

extension APIProviderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__APIProviderTests = [
        ("testDateDecoding", testDateDecoding),
        ("testRequestExecutionErrorResponse", testRequestExecutionErrorResponse),
        ("testRequestExecutionWithVoidResponse", testRequestExecutionWithVoidResponse),
        ("testRequestForResourceLink", testRequestForResourceLink),
        ("testRequestForResourceLinkWithFailure", testRequestForResourceLinkWithFailure),
        ("testRequestWithDataResultSuccess", testRequestWithDataResultSuccess),
        ("testRequestWithDecodableResult", testRequestWithDecodableResult),
        ("testRequestWithDecodableResultFailure", testRequestWithDecodableResultFailure),
    ]
}

extension AddAccessForBetaGroupsToBuildTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AddAccessForBetaGroupsToBuildTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension AddBetaTesterToBetaGroupsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AddBetaTesterToBetaGroupsTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension AddBetaTestersToBetaGroupTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AddBetaTestersToBetaGroupTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension AddBuildsToBetaGroupTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AddBuildsToBetaGroupTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension AddVisibleAppsToUserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AddVisibleAppsToUserTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension AppRelationshipTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AppRelationshipTests = [
        ("test", test),
    ]
}

extension AssignAppEncryptionDeclarationForBuildTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AssignAppEncryptionDeclarationForBuildTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension AssignBetaTesterToBuildsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AssignBetaTesterToBuildsTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension AssignBuildsToAppEncryptionDeclarationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AssignBuildsToAppEncryptionDeclarationTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension AssignIndividualTestersToBuildTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AssignIndividualTestersToBuildTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension BetaGroupRelationshipTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BetaGroupRelationshipTests = [
        ("test", test),
    ]
}

extension BetaTesterRelationshipTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BetaTesterRelationshipTests = [
        ("test", test),
    ]
}

extension BuildRelationshipTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BuildRelationshipTests = [
        ("test", test),
    ]
}

extension CancelUserInvitationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CancelUserInvitationTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension CreateBetaAppLocalizationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CreateBetaAppLocalizationTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension CreateBetaBuildLocalizationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CreateBetaBuildLocalizationTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension CreateBetaGroupTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CreateBetaGroupTests = [
        ("testURLRequest", testURLRequest),
        ("testURLRequestWithDefaultValues", testURLRequestWithDefaultValues),
    ]
}

extension CreateBetaTesterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CreateBetaTesterTests = [
        ("testURLRequestWithBetaGroupIds", testURLRequestWithBetaGroupIds),
        ("testURLRequestWithBuildIds", testURLRequestWithBuildIds),
    ]
}

extension DeleteBetaAppLocalizationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DeleteBetaAppLocalizationTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension DeleteBetaBuildLocalizationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DeleteBetaBuildLocalizationTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension DeleteBetaGroupTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DeleteBetaGroupTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension DeleteBetaTesterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DeleteBetaTesterTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension DownloadFinanceReportsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DownloadFinanceReportsTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension DownloadSalesAndTrendsReportsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DownloadSalesAndTrendsReportsTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetAppEncryptionDeclarationIDForBuildTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetAppEncryptionDeclarationIDForBuildTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetAppResourceIDForAppEncryptionDeclarationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetAppResourceIDForAppEncryptionDeclarationTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetAppResourceIDForBetaAppLocalizationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetAppResourceIDForBetaAppLocalizationTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetAppResourceIDForBetaAppReviewDetailsResourceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetAppResourceIDForBetaAppReviewDetailsResourceTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetAppResourceIDForBetaGroupTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetAppResourceIDForBetaGroupTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetAppResourceIDForBetaLicenseAgreementTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetAppResourceIDForBetaLicenseAgreementTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetAppResourceIDForBuildTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetAppResourceIDForBuildTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetAppResourceIDForPrereleaseVersionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetAppResourceIDForPrereleaseVersionTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetAppResourceIDsForBetaTesterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetAppResourceIDsForBetaTesterTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetAppResourceIDsVisibleToInvitedUserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetAppResourceIDsVisibleToInvitedUserTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetAppStoreVersionPhasedReleaseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetAppStoreVersionPhasedReleaseTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetAppTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetAppTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetBetaAppLocalizationIDsOfAppTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetBetaAppLocalizationIDsOfAppTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetBetaAppReviewDetailsResourceIDForAppTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetBetaAppReviewDetailsResourceIDForAppTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetBetaAppReviewDetailsResourceOfAppTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetBetaAppReviewDetailsResourceOfAppTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetBetaAppReviewSubmissionIDOfBuildTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetBetaAppReviewSubmissionIDOfBuildTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetBetaBuildLocalizationIDsOfBuildTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetBetaBuildLocalizationIDsOfBuildTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetBetaGroupIDsForAppTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetBetaGroupIDsForAppTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetBetaGroupIDsOfBetaTesterGroupsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetBetaGroupIDsOfBetaTesterGroupsTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetBetaLicenseAgreementIDForAppTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetBetaLicenseAgreementIDForAppTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetBetaLicenseAgreementOfAppTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetBetaLicenseAgreementOfAppTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetBetaTesterIDsInBetaGroupTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetBetaTesterIDsInBetaGroupTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetBetaTesterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetBetaTesterTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetBuildBetaDetailsResourceIDForBuildTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetBuildBetaDetailsResourceIDForBuildTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetBuildIDForBetaAppReviewSubmissionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetBuildIDForBetaAppReviewSubmissionTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetBuildIDForBetaBuildLocalizationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetBuildIDForBetaBuildLocalizationTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetBuildIDForBuildBetaDetailTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetBuildIDForBuildBetaDetailTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetBuildIDsInBetaGroupTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetBuildIDsInBetaGroupTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetBuildIDsOfAppTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetBuildIDsOfAppTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetBuildIDsOfPrereleaseVersionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetBuildIDsOfPrereleaseVersionTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetIDsOfBuildsAssignedToBetaTesterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetIDsOfBuildsAssignedToBetaTesterTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetPrereleaseVersionIDsForAppTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetPrereleaseVersionIDsForAppTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetResourceIDsOfIndividualTestersForBuildTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetResourceIDsOfIndividualTestersForBuildTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetResourceIDsOfPrereleaseVersionsForBuildTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetResourceIDsOfPrereleaseVersionsForBuildTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension GetVisibleAppResourceIDsForUserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GetVisibleAppResourceIDsForUserTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension InviteUserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InviteUserTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension JWTRequestsAuthenticatorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JWTRequestsAuthenticatorTests = [
        ("testAuthorizationHeader", testAuthorizationHeader),
        ("testCachedBearer", testCachedBearer),
        ("testExpiredBearer", testExpiredBearer),
    ]
}

extension JWTTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JWTTests = [
        ("testInvalidP8PrivateKey", testInvalidP8PrivateKey),
    ]
}

extension ListAppEncryptionDeclarationsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListAppEncryptionDeclarationsTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ListAppInfosForAppTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListAppInfosForAppTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ListAppStoreVersionLocalizationsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListAppStoreVersionLocalizationsTests = [
        ("testEmptyParamsURLRequest", testEmptyParamsURLRequest),
        ("testFilledParamsURLRequest", testFilledParamsURLRequest),
        ("testURLRequestMethod", testURLRequestMethod),
    ]
}

extension ListAppStoreVersionsForAppTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListAppStoreVersionsForAppTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ListAppsForBetaTesterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListAppsForBetaTesterTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ListAppsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListAppsTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ListAppsVisibleToInvitedUserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListAppsVisibleToInvitedUserTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ListAppsVisibleToUserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListAppsVisibleToUserTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ListBetaAppLocalizationsOfAppTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListBetaAppLocalizationsOfAppTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ListBetaAppLocalizationsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListBetaAppLocalizationsTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ListBetaAppReviewDetailsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListBetaAppReviewDetailsTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ListBetaAppReviewSubmissionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListBetaAppReviewSubmissionsTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ListBetaBuildLocalizationsOfBuildTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListBetaBuildLocalizationsOfBuildTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ListBetaBuildLocalizationsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListBetaBuildLocalizationsTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ListBetaGroupsForAppTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListBetaGroupsForAppTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ListBetaGroupsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListBetaGroupsTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ListBetaGroupsToWhichBetaTesterBelongsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListBetaGroupsToWhichBetaTesterBelongsTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ListBetaLicenseAgreementsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListBetaLicenseAgreementsTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ListBetaTestersInBetaGroupTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListBetaTestersInBetaGroupTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ListBetaTestersTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListBetaTestersTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ListBuildBetaDetailsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListBuildBetaDetailsTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ListBuildsAssignedToBetaTesterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListBuildsAssignedToBetaTesterTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ListBuildsForBetaGroupTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListBuildsForBetaGroupTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ListBuildsOfAppTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListBuildsOfAppTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ListBuildsOfPrereleaseVersionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListBuildsOfPrereleaseVersionTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ListBuildsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListBuildsTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ListBundleIdsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListBundleIdsTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ListIndividualTestersForBuildTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListIndividualTestersForBuildTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ListInvitedUsersTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListInvitedUsersTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ListPrereleaseVersionsForAppTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListPrereleaseVersionsForAppTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ListPrereleaseVersionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListPrereleaseVersionsTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ListUsersTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListUsersTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ModifyBetaAppLocalizationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ModifyBetaAppLocalizationTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ModifyBetaAppReviewDetailTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ModifyBetaAppReviewDetailTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ModifyBetaBuildLocalizationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ModifyBetaBuildLocalizationTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ModifyBetaGroupTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ModifyBetaGroupTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ModifyBetaLicenseAgreementTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ModifyBetaLicenseAgreementTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ModifyBuildBetaDetailTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ModifyBuildBetaDetailTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ModifyBuildTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ModifyBuildTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ModifyUserAccountTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ModifyUserAccountTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension NestableQueryParameterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NestableQueryParameterTests = [
        ("testNestableQueryParameter", testNestableQueryParameter),
    ]
}

extension PreReleaseVersionRelationshipTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PreReleaseVersionRelationshipTests = [
        ("test", test),
    ]
}

extension ProfileRelationshipTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ProfileRelationshipTests = [
        ("testEncoding", testEncoding),
    ]
}

extension ProfilesResponseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ProfilesResponseTests = [
        ("testDecodeIncludeBundleId", testDecodeIncludeBundleId),
        ("testDecodeIncludeCertificates", testDecodeIncludeCertificates),
        ("testDecodeIncludeDevices", testDecodeIncludeDevices),
        ("testDecodeNonEmpty", testDecodeNonEmpty),
    ]
}

extension ReadAppEncryptionDeclarationInformationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReadAppEncryptionDeclarationInformationTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ReadAppEncryptionDeclarationOfBuildTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReadAppEncryptionDeclarationOfBuildTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ReadAppInfoOfAppTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReadAppInfoOfAppTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ReadAppInformationOfAppEncryptionDeclarationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReadAppInformationOfAppEncryptionDeclarationTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ReadAppInformationOfBetaAppLocalizationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReadAppInformationOfBetaAppLocalizationTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ReadAppInformationOfBetaAppReviewDetailTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReadAppInformationOfBetaAppReviewDetailTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ReadAppInformationOfBetaGroupTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReadAppInformationOfBetaGroupTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ReadAppInformationOfBetaLicenseAgreementTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReadAppInformationOfBetaLicenseAgreementTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ReadAppInformationOfBuildTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReadAppInformationOfBuildTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ReadAppInformationOfPrereleaseVersionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReadAppInformationOfPrereleaseVersionTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ReadBetaAppLocalizationInformationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReadBetaAppLocalizationInformationTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ReadBetaAppReviewDetailInformationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReadBetaAppReviewDetailInformationTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ReadBetaAppReviewSubmissionInformationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReadBetaAppReviewSubmissionInformationTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ReadBetaAppReviewSubmissionOfBuildTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReadBetaAppReviewSubmissionOfBuildTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ReadBetaBuildLocalizationInformationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReadBetaBuildLocalizationInformationTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ReadBetaGroupInformationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReadBetaGroupInformationTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ReadBetaLicenseAgreementInformationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReadBetaLicenseAgreementInformationTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ReadBuildBetaDetailInformationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReadBuildBetaDetailInformationTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ReadBuildBetaDetailsInformationOfBuildTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReadBuildBetaDetailsInformationOfBuildTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ReadBuildInformationOfBetaAppReviewSubmissionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReadBuildInformationOfBetaAppReviewSubmissionTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ReadBuildInformationOfBetaBuildLocalizationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReadBuildInformationOfBetaBuildLocalizationTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ReadBuildInformationOfBuildBetaDetailTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReadBuildInformationOfBuildBetaDetailTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ReadBuildInformationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReadBuildInformationTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ReadPrereleaseVersionInformationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReadPrereleaseVersionInformationTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ReadPrereleaseVersionOfBuildTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReadPrereleaseVersionOfBuildTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ReadUserInformationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReadUserInformationTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ReadUserInvitationInformationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReadUserInvitationInformationTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension RemoveAccessForBetaGroupsToBuildTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RemoveAccessForBetaGroupsToBuildTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension RemoveBetaTesterAccessToAppsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RemoveBetaTesterAccessToAppsTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension RemoveBetaTesterFromBetaGroupsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RemoveBetaTesterFromBetaGroupsTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension RemoveBetaTestersFromBetaGroupTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RemoveBetaTestersFromBetaGroupTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension RemoveBetaTestersFromGroupsAndBuildsOfAppTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RemoveBetaTestersFromGroupsAndBuildsOfAppTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension RemoveBuildsFromBetaGroupTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RemoveBuildsFromBetaGroupTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension RemoveIndividualTestersFromBuildTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RemoveIndividualTestersFromBuildTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension RemoveUserAccountTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RemoveUserAccountTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension RemoveVisibleAppsFromUserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RemoveVisibleAppsFromUserTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension ReplaceListOfVisibleAppsForUserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReplaceListOfVisibleAppsForUserTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension SendInvitationToBetaTesterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SendInvitationToBetaTesterTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension SendNotificationOfAvailableBuildTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SendNotificationOfAvailableBuildTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension SubmitAppForBetaReviewTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SubmitAppForBetaReviewTests = [
        ("testURLRequest", testURLRequest),
    ]
}

extension UnassignBetaTesterFromBuildsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UnassignBetaTesterFromBuildsTests = [
        ("testURLRequest", testURLRequest),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(APIProviderTests.__allTests__APIProviderTests),
        testCase(AddAccessForBetaGroupsToBuildTests.__allTests__AddAccessForBetaGroupsToBuildTests),
        testCase(AddBetaTesterToBetaGroupsTests.__allTests__AddBetaTesterToBetaGroupsTests),
        testCase(AddBetaTestersToBetaGroupTests.__allTests__AddBetaTestersToBetaGroupTests),
        testCase(AddBuildsToBetaGroupTests.__allTests__AddBuildsToBetaGroupTests),
        testCase(AddVisibleAppsToUserTests.__allTests__AddVisibleAppsToUserTests),
        testCase(AppRelationshipTests.__allTests__AppRelationshipTests),
        testCase(AssignAppEncryptionDeclarationForBuildTests.__allTests__AssignAppEncryptionDeclarationForBuildTests),
        testCase(AssignBetaTesterToBuildsTests.__allTests__AssignBetaTesterToBuildsTests),
        testCase(AssignBuildsToAppEncryptionDeclarationTests.__allTests__AssignBuildsToAppEncryptionDeclarationTests),
        testCase(AssignIndividualTestersToBuildTests.__allTests__AssignIndividualTestersToBuildTests),
        testCase(BetaGroupRelationshipTests.__allTests__BetaGroupRelationshipTests),
        testCase(BetaTesterRelationshipTests.__allTests__BetaTesterRelationshipTests),
        testCase(BuildRelationshipTests.__allTests__BuildRelationshipTests),
        testCase(CancelUserInvitationTests.__allTests__CancelUserInvitationTests),
        testCase(CreateBetaAppLocalizationTests.__allTests__CreateBetaAppLocalizationTests),
        testCase(CreateBetaBuildLocalizationTests.__allTests__CreateBetaBuildLocalizationTests),
        testCase(CreateBetaGroupTests.__allTests__CreateBetaGroupTests),
        testCase(CreateBetaTesterTests.__allTests__CreateBetaTesterTests),
        testCase(DeleteBetaAppLocalizationTests.__allTests__DeleteBetaAppLocalizationTests),
        testCase(DeleteBetaBuildLocalizationTests.__allTests__DeleteBetaBuildLocalizationTests),
        testCase(DeleteBetaGroupTests.__allTests__DeleteBetaGroupTests),
        testCase(DeleteBetaTesterTests.__allTests__DeleteBetaTesterTests),
        testCase(DownloadFinanceReportsTests.__allTests__DownloadFinanceReportsTests),
        testCase(DownloadSalesAndTrendsReportsTests.__allTests__DownloadSalesAndTrendsReportsTests),
        testCase(GetAppEncryptionDeclarationIDForBuildTests.__allTests__GetAppEncryptionDeclarationIDForBuildTests),
        testCase(GetAppResourceIDForAppEncryptionDeclarationTests.__allTests__GetAppResourceIDForAppEncryptionDeclarationTests),
        testCase(GetAppResourceIDForBetaAppLocalizationTests.__allTests__GetAppResourceIDForBetaAppLocalizationTests),
        testCase(GetAppResourceIDForBetaAppReviewDetailsResourceTests.__allTests__GetAppResourceIDForBetaAppReviewDetailsResourceTests),
        testCase(GetAppResourceIDForBetaGroupTests.__allTests__GetAppResourceIDForBetaGroupTests),
        testCase(GetAppResourceIDForBetaLicenseAgreementTests.__allTests__GetAppResourceIDForBetaLicenseAgreementTests),
        testCase(GetAppResourceIDForBuildTests.__allTests__GetAppResourceIDForBuildTests),
        testCase(GetAppResourceIDForPrereleaseVersionTests.__allTests__GetAppResourceIDForPrereleaseVersionTests),
        testCase(GetAppResourceIDsForBetaTesterTests.__allTests__GetAppResourceIDsForBetaTesterTests),
        testCase(GetAppResourceIDsVisibleToInvitedUserTests.__allTests__GetAppResourceIDsVisibleToInvitedUserTests),
        testCase(GetAppStoreVersionPhasedReleaseTests.__allTests__GetAppStoreVersionPhasedReleaseTests),
        testCase(GetAppTests.__allTests__GetAppTests),
        testCase(GetBetaAppLocalizationIDsOfAppTests.__allTests__GetBetaAppLocalizationIDsOfAppTests),
        testCase(GetBetaAppReviewDetailsResourceIDForAppTests.__allTests__GetBetaAppReviewDetailsResourceIDForAppTests),
        testCase(GetBetaAppReviewDetailsResourceOfAppTests.__allTests__GetBetaAppReviewDetailsResourceOfAppTests),
        testCase(GetBetaAppReviewSubmissionIDOfBuildTests.__allTests__GetBetaAppReviewSubmissionIDOfBuildTests),
        testCase(GetBetaBuildLocalizationIDsOfBuildTests.__allTests__GetBetaBuildLocalizationIDsOfBuildTests),
        testCase(GetBetaGroupIDsForAppTests.__allTests__GetBetaGroupIDsForAppTests),
        testCase(GetBetaGroupIDsOfBetaTesterGroupsTests.__allTests__GetBetaGroupIDsOfBetaTesterGroupsTests),
        testCase(GetBetaLicenseAgreementIDForAppTests.__allTests__GetBetaLicenseAgreementIDForAppTests),
        testCase(GetBetaLicenseAgreementOfAppTests.__allTests__GetBetaLicenseAgreementOfAppTests),
        testCase(GetBetaTesterIDsInBetaGroupTests.__allTests__GetBetaTesterIDsInBetaGroupTests),
        testCase(GetBetaTesterTests.__allTests__GetBetaTesterTests),
        testCase(GetBuildBetaDetailsResourceIDForBuildTests.__allTests__GetBuildBetaDetailsResourceIDForBuildTests),
        testCase(GetBuildIDForBetaAppReviewSubmissionTests.__allTests__GetBuildIDForBetaAppReviewSubmissionTests),
        testCase(GetBuildIDForBetaBuildLocalizationTests.__allTests__GetBuildIDForBetaBuildLocalizationTests),
        testCase(GetBuildIDForBuildBetaDetailTests.__allTests__GetBuildIDForBuildBetaDetailTests),
        testCase(GetBuildIDsInBetaGroupTests.__allTests__GetBuildIDsInBetaGroupTests),
        testCase(GetBuildIDsOfAppTests.__allTests__GetBuildIDsOfAppTests),
        testCase(GetBuildIDsOfPrereleaseVersionTests.__allTests__GetBuildIDsOfPrereleaseVersionTests),
        testCase(GetIDsOfBuildsAssignedToBetaTesterTests.__allTests__GetIDsOfBuildsAssignedToBetaTesterTests),
        testCase(GetPrereleaseVersionIDsForAppTests.__allTests__GetPrereleaseVersionIDsForAppTests),
        testCase(GetResourceIDsOfIndividualTestersForBuildTests.__allTests__GetResourceIDsOfIndividualTestersForBuildTests),
        testCase(GetResourceIDsOfPrereleaseVersionsForBuildTests.__allTests__GetResourceIDsOfPrereleaseVersionsForBuildTests),
        testCase(GetVisibleAppResourceIDsForUserTests.__allTests__GetVisibleAppResourceIDsForUserTests),
        testCase(InviteUserTests.__allTests__InviteUserTests),
        testCase(JWTRequestsAuthenticatorTests.__allTests__JWTRequestsAuthenticatorTests),
        testCase(JWTTests.__allTests__JWTTests),
        testCase(ListAppEncryptionDeclarationsTests.__allTests__ListAppEncryptionDeclarationsTests),
        testCase(ListAppInfosForAppTests.__allTests__ListAppInfosForAppTests),
        testCase(ListAppStoreVersionLocalizationsTests.__allTests__ListAppStoreVersionLocalizationsTests),
        testCase(ListAppStoreVersionsForAppTests.__allTests__ListAppStoreVersionsForAppTests),
        testCase(ListAppsForBetaTesterTests.__allTests__ListAppsForBetaTesterTests),
        testCase(ListAppsTests.__allTests__ListAppsTests),
        testCase(ListAppsVisibleToInvitedUserTests.__allTests__ListAppsVisibleToInvitedUserTests),
        testCase(ListAppsVisibleToUserTests.__allTests__ListAppsVisibleToUserTests),
        testCase(ListBetaAppLocalizationsOfAppTests.__allTests__ListBetaAppLocalizationsOfAppTests),
        testCase(ListBetaAppLocalizationsTests.__allTests__ListBetaAppLocalizationsTests),
        testCase(ListBetaAppReviewDetailsTests.__allTests__ListBetaAppReviewDetailsTests),
        testCase(ListBetaAppReviewSubmissionsTests.__allTests__ListBetaAppReviewSubmissionsTests),
        testCase(ListBetaBuildLocalizationsOfBuildTests.__allTests__ListBetaBuildLocalizationsOfBuildTests),
        testCase(ListBetaBuildLocalizationsTests.__allTests__ListBetaBuildLocalizationsTests),
        testCase(ListBetaGroupsForAppTests.__allTests__ListBetaGroupsForAppTests),
        testCase(ListBetaGroupsTests.__allTests__ListBetaGroupsTests),
        testCase(ListBetaGroupsToWhichBetaTesterBelongsTests.__allTests__ListBetaGroupsToWhichBetaTesterBelongsTests),
        testCase(ListBetaLicenseAgreementsTests.__allTests__ListBetaLicenseAgreementsTests),
        testCase(ListBetaTestersInBetaGroupTests.__allTests__ListBetaTestersInBetaGroupTests),
        testCase(ListBetaTestersTests.__allTests__ListBetaTestersTests),
        testCase(ListBuildBetaDetailsTests.__allTests__ListBuildBetaDetailsTests),
        testCase(ListBuildsAssignedToBetaTesterTests.__allTests__ListBuildsAssignedToBetaTesterTests),
        testCase(ListBuildsForBetaGroupTests.__allTests__ListBuildsForBetaGroupTests),
        testCase(ListBuildsOfAppTests.__allTests__ListBuildsOfAppTests),
        testCase(ListBuildsOfPrereleaseVersionTests.__allTests__ListBuildsOfPrereleaseVersionTests),
        testCase(ListBuildsTests.__allTests__ListBuildsTests),
        testCase(ListBundleIdsTests.__allTests__ListBundleIdsTests),
        testCase(ListIndividualTestersForBuildTests.__allTests__ListIndividualTestersForBuildTests),
        testCase(ListInvitedUsersTests.__allTests__ListInvitedUsersTests),
        testCase(ListPrereleaseVersionsForAppTests.__allTests__ListPrereleaseVersionsForAppTests),
        testCase(ListPrereleaseVersionsTests.__allTests__ListPrereleaseVersionsTests),
        testCase(ListUsersTests.__allTests__ListUsersTests),
        testCase(ModifyBetaAppLocalizationTests.__allTests__ModifyBetaAppLocalizationTests),
        testCase(ModifyBetaAppReviewDetailTests.__allTests__ModifyBetaAppReviewDetailTests),
        testCase(ModifyBetaBuildLocalizationTests.__allTests__ModifyBetaBuildLocalizationTests),
        testCase(ModifyBetaGroupTests.__allTests__ModifyBetaGroupTests),
        testCase(ModifyBetaLicenseAgreementTests.__allTests__ModifyBetaLicenseAgreementTests),
        testCase(ModifyBuildBetaDetailTests.__allTests__ModifyBuildBetaDetailTests),
        testCase(ModifyBuildTests.__allTests__ModifyBuildTests),
        testCase(ModifyUserAccountTests.__allTests__ModifyUserAccountTests),
        testCase(NestableQueryParameterTests.__allTests__NestableQueryParameterTests),
        testCase(PreReleaseVersionRelationshipTests.__allTests__PreReleaseVersionRelationshipTests),
        testCase(ProfileRelationshipTests.__allTests__ProfileRelationshipTests),
        testCase(ProfilesResponseTests.__allTests__ProfilesResponseTests),
        testCase(ReadAppEncryptionDeclarationInformationTests.__allTests__ReadAppEncryptionDeclarationInformationTests),
        testCase(ReadAppEncryptionDeclarationOfBuildTests.__allTests__ReadAppEncryptionDeclarationOfBuildTests),
        testCase(ReadAppInfoOfAppTests.__allTests__ReadAppInfoOfAppTests),
        testCase(ReadAppInformationOfAppEncryptionDeclarationTests.__allTests__ReadAppInformationOfAppEncryptionDeclarationTests),
        testCase(ReadAppInformationOfBetaAppLocalizationTests.__allTests__ReadAppInformationOfBetaAppLocalizationTests),
        testCase(ReadAppInformationOfBetaAppReviewDetailTests.__allTests__ReadAppInformationOfBetaAppReviewDetailTests),
        testCase(ReadAppInformationOfBetaGroupTests.__allTests__ReadAppInformationOfBetaGroupTests),
        testCase(ReadAppInformationOfBetaLicenseAgreementTests.__allTests__ReadAppInformationOfBetaLicenseAgreementTests),
        testCase(ReadAppInformationOfBuildTests.__allTests__ReadAppInformationOfBuildTests),
        testCase(ReadAppInformationOfPrereleaseVersionTests.__allTests__ReadAppInformationOfPrereleaseVersionTests),
        testCase(ReadBetaAppLocalizationInformationTests.__allTests__ReadBetaAppLocalizationInformationTests),
        testCase(ReadBetaAppReviewDetailInformationTests.__allTests__ReadBetaAppReviewDetailInformationTests),
        testCase(ReadBetaAppReviewSubmissionInformationTests.__allTests__ReadBetaAppReviewSubmissionInformationTests),
        testCase(ReadBetaAppReviewSubmissionOfBuildTests.__allTests__ReadBetaAppReviewSubmissionOfBuildTests),
        testCase(ReadBetaBuildLocalizationInformationTests.__allTests__ReadBetaBuildLocalizationInformationTests),
        testCase(ReadBetaGroupInformationTests.__allTests__ReadBetaGroupInformationTests),
        testCase(ReadBetaLicenseAgreementInformationTests.__allTests__ReadBetaLicenseAgreementInformationTests),
        testCase(ReadBuildBetaDetailInformationTests.__allTests__ReadBuildBetaDetailInformationTests),
        testCase(ReadBuildBetaDetailsInformationOfBuildTests.__allTests__ReadBuildBetaDetailsInformationOfBuildTests),
        testCase(ReadBuildInformationOfBetaAppReviewSubmissionTests.__allTests__ReadBuildInformationOfBetaAppReviewSubmissionTests),
        testCase(ReadBuildInformationOfBetaBuildLocalizationTests.__allTests__ReadBuildInformationOfBetaBuildLocalizationTests),
        testCase(ReadBuildInformationOfBuildBetaDetailTests.__allTests__ReadBuildInformationOfBuildBetaDetailTests),
        testCase(ReadBuildInformationTests.__allTests__ReadBuildInformationTests),
        testCase(ReadPrereleaseVersionInformationTests.__allTests__ReadPrereleaseVersionInformationTests),
        testCase(ReadPrereleaseVersionOfBuildTests.__allTests__ReadPrereleaseVersionOfBuildTests),
        testCase(ReadUserInformationTests.__allTests__ReadUserInformationTests),
        testCase(ReadUserInvitationInformationTests.__allTests__ReadUserInvitationInformationTests),
        testCase(RemoveAccessForBetaGroupsToBuildTests.__allTests__RemoveAccessForBetaGroupsToBuildTests),
        testCase(RemoveBetaTesterAccessToAppsTests.__allTests__RemoveBetaTesterAccessToAppsTests),
        testCase(RemoveBetaTesterFromBetaGroupsTests.__allTests__RemoveBetaTesterFromBetaGroupsTests),
        testCase(RemoveBetaTestersFromBetaGroupTests.__allTests__RemoveBetaTestersFromBetaGroupTests),
        testCase(RemoveBetaTestersFromGroupsAndBuildsOfAppTests.__allTests__RemoveBetaTestersFromGroupsAndBuildsOfAppTests),
        testCase(RemoveBuildsFromBetaGroupTests.__allTests__RemoveBuildsFromBetaGroupTests),
        testCase(RemoveIndividualTestersFromBuildTests.__allTests__RemoveIndividualTestersFromBuildTests),
        testCase(RemoveUserAccountTests.__allTests__RemoveUserAccountTests),
        testCase(RemoveVisibleAppsFromUserTests.__allTests__RemoveVisibleAppsFromUserTests),
        testCase(ReplaceListOfVisibleAppsForUserTests.__allTests__ReplaceListOfVisibleAppsForUserTests),
        testCase(SendInvitationToBetaTesterTests.__allTests__SendInvitationToBetaTesterTests),
        testCase(SendNotificationOfAvailableBuildTests.__allTests__SendNotificationOfAvailableBuildTests),
        testCase(SubmitAppForBetaReviewTests.__allTests__SubmitAppForBetaReviewTests),
        testCase(UnassignBetaTesterFromBuildsTests.__allTests__UnassignBetaTesterFromBuildsTests),
    ]
}
#endif
